[package]
name = "fatimg"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3.0.5", features = ["derive"] }
anyhow = "1.0"
env_logger = "0.8"
fscommon = "0.1"

[dependencies.fatfs]
git = "https://github.com/rafalh/rust-fatfs"
rev = "87fc1ed5074a32b4e0344fcdde77359ef9e75432"
